### PR TITLE
Issue tab page not found

### PR DESCRIPTION
**Pull request by FayasNoushad**

### CODE REVIEW

**Comment by FayasNoushad** [comment]
Please turn on issues or discussion.

**Review by FayasNoushad — COMMENTED** [review]
@delivrance, Can you merge this?

**Comment by bilal-08** [comment]
Ummm
Since issue tab is not found i will say this here


Please add raw format cause mobile device can't select all the text for copy

**Comment by Krishna-Singhal** [comment]
> Ummm Since issue tab is not found i will say this here
> 
> Please add raw format cause mobile device can't select all the text for copy

htpps://nekobin.com/raw/{your_key_here}

**Comment by Justinzobel** [comment]
I think this may be abandoned. Sad really as it's a nice pastebin.

**Pull request closed without merging**
